version: "3.9"
services:
  nginx:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - "80:80"
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
