version: "3.9"
services:
  nginx:
    image: docker.pkg.github.com/planckproject/mental-wellbeing-resources/nginx:latest
    ports:
      - "80:80"
    depends_on:
      - api
      - frontend
    volume:
      - /etc/letsencrypt:/etc/letsencrypt
      - /etc/nginx:./nginx-conf
  api:
    image: docker.pkg.github.com/planckproject/mental-wellbeing-resources/api:latest
    environment:
      - "MONGO_URI=${MONGO_URI}"
  frontend:
    image: docker.pkg.github.com/planckproject/mental-wellbeing-resources/frontend:latest
    environment:
      - "API_URI=api:8082"
